### ISSUE TITLE
run pkgcheck on pkgcheck

### ISSUE THREAD

**Issue by mpadge** [ropensci-review-tools/pkgcheck#180]
Was so busy checking everything outside this package that I completely negected to run pkgcheck on itself. Current results look like this:

## Checks for [pkgcheck (v0.1.1.026)](https://github.com/ropensci-review-tools/pkgcheck)

git hash: [6dd7b3ab](https://github.com/ropensci-review-tools/pkgcheck/tree/6dd7b3ab4902c9f1a9fdb8760eaa62e4ce93fa12)

- :heavy_check_mark: Package name is available
- :heavy_check_mark: has a 'codemeta.json' file.
- :heavy_check_mark: has a 'contributing' file.
- :heavy_multiplication_x: The following functions have no documented return values: [print.pkgcheck, read_pkg_guide]
- :heavy_check_mark: uses 'roxygen2'.
- :heavy_check_mark: 'DESCRIPTION' has a URL field.
- :heavy_check_mark: 'DESCRIPTION' has a BugReports field.
- :heavy_check_mark: Package has at least one HTML vignette
- :heavy_multiplication_x: These functions do not have examples: [checks_to_markdown, get_default_github_branch, get_gh_token, get_latest_commit, logfile_names, pkgcheck_bg, pkgcheck, print.pkgcheck, read_pkg_guide, render_markdown].
- :heavy_check_mark: Package has continuous integration checks.
- :heavy_multiplication_x: Package coverage is 68.6% (should be at least 75%).
- :heavy_check_mark: R CMD check found no errors.
- :heavy_check_mark: R CMD check found no warnings.
- :eyes: Function names are duplicated in other packages

---

# TODO

- [x] Document return values for [print.pkgcheck, read_pkg_guide]
- [x] Add examples for all functions which do not have them
- [ ] ~~Increase package coverage to > 75%~~ Nope, coverage is actually 86%; that was a local glitch.
- [x] Fix duplicated function name: `knitr::render_markdown()`

**Comment by mpadge** [comment]
First run is in (#181), and all is good, except coverage is ... 74.8%! Just have to increase that a tiny bit to close this.
