### ISSUE TITLE
In vignette about adding checks, add whether one can consider the package to be installed

### ISSUE THREAD

**Issue by maelle** [ropensci-review-tools/pkgcheck#61]
I.e. can checks used tools for installed packages or do they need to rather do some sort of parsing / static analyses?

**Comment by maelle** [comment]
Maybe also comment on/document the kind of metadata that's extracted by default and can be re-used in some checks.

**Comment by mpadge** [comment]
This will be partly addressed via #40, especially via local control of which tests are run. Currently the only tests requiring installation are the [`rcmdcheck`](https://github.com/r-Lib/rcmdcheck) and [`covr`](https://github.com/r-lib/covr) parts of [`goodpractice`](https://github.com/MangoTheCat/goodpractice). They are nevertheless core parts, and `pgkcheck` currently presumes installation to be required.

That said, I personally suspect once user control of tests has been implemented (#40), I'll often resort to frequent static-only checks, only resorting to the full checks when i need to. Each check will have some kind of metadata - possibly along the lines of the values passed to the [`make_check()` function of `goodpractice`](https://github.com/MangoTheCat/goodpractice/blob/main/R/customization.R), which have ["description", "type", and "pattern" fields](https://github.com/MangoTheCat/goodpractice/blob/main/R/chk_rcmdcheck.R). Something along the lines of the meta-data approach there will likely be adopted here, with at least one additional meta-data flag, `requires_installation`. That would be really useful!

---

> Maybe also comment on/document the kind of metadata that's extracted by default and can be re-used in some checks.

Yes indeed. That also requires documenting direct (or maybe "flat") tests versus hierarchical tests. Direct tests are like your `has_scrap`; hierarchical tests are like `goodpractice` and `pkgstats`. All of that needs documentation, but that can't sensibly be done until we know the ultimate form that these hierarchies are going to take. This issue definitely needs to remain open to address:

## TODO

- [ ] Structures for check metadata
- [ ] `requires_installation` flag within metadata
- [ ] Consistent system for hierarchical checks
- [ ] Documentation of hierarchical checks
- [ ] Documentation of all information currently extracted within checks (yet not necessarily "exported" to printed results)
